# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Deploy a new version to a Google Play track. Usage: fastlane deploy track:internal"
  lane :deploy do |options|
    track = options[:track] || "internal"
    UI.user_error!("Unknown track '#{track}'. Must be one of: internal, beta, production") unless %w[internal beta production].include?(track)

    aab_path = Dir.glob(File.expand_path("../app/build/outputs/bundle/productionRelease/*.aab", __dir__)).last
    UI.user_error!("No AAB found in app/build/outputs/bundle/productionRelease/") unless aab_path

    upload_to_play_store(
        track: track,
        aab: aab_path,
        release_status: "completed"
    )
  end
end
